```typescript
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.42.0";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// Helper function to create a Supabase client
const getSupabaseClient = (req: Request) => {
  const authHeader = req.headers.get('Authorization')!;
  const supabaseClient = createClient(
    Deno.env.get('SUPABASE_URL') ?? '',
    Deno.env.get('SUPABASE_ANON_KEY') ?? '',
    {
      global: {
        headers: { Authorization: authHeader },
      },
    }
  );
  return supabaseClient;
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const url = new URL(req.url);
    const path = url.pathname;
    const supabase = getSupabaseClient(req);

    // GET /api/recipes
    if (path === '/api/recipes' && req.method === 'GET') {
      const isVegetarian = url.searchParams.get('is_vegetarian');
      const isGlutenFree = url.searchParams.get('is_gluten_free');
      const limit = parseInt(url.searchParams.get('limit') || '20', 10);
      const offset = parseInt(url.searchParams.get('offset') || '0', 10);

      let query = supabase.from('recipes').select('*');

      if (isVegetarian === 'true') {
        query = query.eq('is_vegetarian', true);
      }
      if (isGlutenFree === 'true') {
        query = query.eq('is_gluten_free', true);
      }

      query = query.range(offset, offset + limit - 1);

      const { data, error } = await query;

      if (error) throw error;

      return new Response(JSON.stringify(data), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // GET /api/recipes/{id}
    if (path.startsWith('/api/recipes/') && req.method === 'GET') {
      const id = path.split('/api/recipes/')[1];

      const { data, error } = await supabase
        .from('recipes')
        .select('*')
        .eq('id', id)
        .single();

      if (error) throw error;
      if (!data) {
        return new Response(JSON.stringify({ error: 'Recipe not found' }), {
          status: 404,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
      }

      return new Response(JSON.stringify(data), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // POST /api/recipes/generate
    if (path === '/api/recipes/generate' && req.method === 'POST') {
      const { preferences, count } = await req.json();

      // Here you would integrate with an external AI API
      // For demonstration, we'll return mock data.
      const generatedRecipes = Array.from({ length: count || 1 }).map((_, i) => ({
        id: crypto.randomUUID(),
        title: `AI Generated Recipe ${i + 1}`,
        description: `A delicious recipe generated by AI based on your preferences.`,
        image_url: `https://picsum.photos/seed/${crypto.randomUUID()}/400/300`,
        is_vegetarian: preferences?.dietary?.includes('vegetarian') || false,
        is_gluten_free: preferences?.dietary?.includes('gluten-free') || false,
        ingredients: ["Ingredient 1", "Ingredient 2"],
        instructions: ["Step 1", "Step 2"],
        prep_time